### ISSUE TITLE
login部分代码提问

### ISSUE THREAD

**Issue by xlwy77** [Hemlock-Software/frontend#5]
现在别的跳转和界面都已经完成，目前的问题是我不知道现在login的验证应该如何通过
返回res.code始终是400，我需要怎么修改呢？
import React, { useState } from 'react'
import Box from '@mui/material/Box'
import TextField from '@mui/material/TextField'
import { Button } from '@mui/material'
import Typography from '@mui/material/Typography'

import { UserLogin } from '../../../services/api'
import { useNavigate } from 'react-router'
function Login() {
  const [mail, setMail] = useState('')
  const [password, setPassword] = useState('')
  const navigate = useNavigate()

  function onMail(e) {
    //console.log(e.target.value)
    setMail(e.target.value)
  }
  function onPassword(e) {
    //console.log(e.target.value)
    setPassword(e.target.value)
  }

  function submitLogin() {
    const postData = {
      mail: mail,
      password: password,
    }
    console.log(postData)
    UserLogin({ info: postData})
      .then((response) => {
        // 请求成功的处理
        if (response.code != '200') {
          console.error(response.msg)
        } else {
          navigate('../')
        }
        console.log(response)
      })
      .catch((error) => {
        // 请求失败的处理
        console.error(error)
      })
  }
  function submitRegister(){
    navigate('/register')
  }
  function submitRetrievePassword(){
    navigate('/retrievePassword')
  }
  return (
    <center>
      <br />
      <Typography variant="h3" gutterBottom color={'#1976d2'}>
        Login
      </Typography>
      <Box
        component="form"
        sx={{
          '& > :not(style)': { m: 1, width: '25ch' },
        }}
        noValidate
        autoComplete="off">
        <TextField
          id="standard-basic"
          label="E-mail address"
          variant="standard"
          onChange={onMail}
        />
        <br />
        <TextField
          id="standard-basic"
          label="password"
          variant="standard"
          onChange={onPassword}
        />
        <br />
        <Button onClick={submitLogin}>Login</Button>
        <br />
        <Button onClick={submitRegister}>register</Button>
        <br />
        <Button onClick={submitRetrievePassword}>retrieve Password</Button>
      </Box>
    </center>
  )
}

export default Login

**Comment by IEeyaa** [comment]
当时login时候使用的数据是什么？没有注册的情况下后端应该不会把数据存入，发送包的流程我看了一下基本没问题，可以用postman发一下包，如果还是错的再跟后端商量原因

**Comment by xlwy77** [comment]
已经完成后提交了
