### ISSUE TITLE
注册端细节问题

### ISSUE THREAD

**Issue by IEeyaa** [Hemlock-Software/frontend#8]
1.password输入的时候可以直接看到，这个需要改一下
2.我把你的代码改了一下，有一个地方你可以留意一下，我现在把更改函数全部写在onChange里面了（没有像你之前一样用onMail来引出一个函数修改mail等，这个看你个人喜好就好）
3.login的密码用了SHA256加密传输，那register也应该一样，这个可以和王奕博以及后端协调一下
4.布局问题：我个人觉得nickname应该在最上面，以及还得加一行checkpassword确认密码
5.前端验证可以做起来了，有以下几点
5.1 nickname可以为空
5.2 邮箱不能为空，必须符合邮箱范式（可以网上查一下，起码得有个@）
5.3 password需要符合这个范式（6-16位，必须包含且只能出现英文和数字【特别是不允许特殊符号来实现sql注入攻击】）
5.4 password和checkpassword要做校验

**Comment by fffelix-jan** [comment]
For 5.3, preventing special characters is not a proper solution for preventing SQL injection attacks. You would have to use parameterized queries on the server side to prevent that. This way, users are free to use special characters such as `'` in their password.
